#!/usr/bin/env bash
# Idempotent installer for streamdeck-agentdeck.
# Installs: udev rule (uaccess), Python deps, deck.py, and the systemd --user service.
# Use --configure for the first-time interactive setup wizard.
set -euo pipefail

SRC="$(cd "$(dirname "$0")" && pwd)"
DEST="$HOME/streamdeck-agentdeck"
UNIT="streamdeck-agentdeck.service"
USER_UNIT_DIR="$HOME/.config/systemd/user"
CONFIG_DIR="$HOME/.config/streamdeck-agentdeck"
CONFIG_FILE="$CONFIG_DIR/config.toml"

usage() { echo "Usage: $0 [--configure] [--force]"; exit "${1:-0}"; }

do_configure() {
  echo
  echo " Stream Deck Agentdeck — Initial Setup"
  echo " ─────────────────────────────────────"
  read -rp " Latitude  (e.g. 40.7128): " LAT
  read -rp " Longitude (e.g. -74.0060): " LON
  read -rp " City label (e.g. New York): " CITY
  read -rp " SSH host for agent (blank=local): " SSH_HOST

  # ponytail: simple awk validation — upgrade: python3 -c 'import sys; sys.exit(0 if -90<=float(sys.argv[1])<=90 else 1)' if edge cases appear
  awk -v l="$LAT" 'BEGIN{exit !(l+0==l && l>=-90 && l<=90)}' \
    || { echo "Invalid latitude (must be -90..90)" >&2; exit 1; }
  awk -v l="$LON" 'BEGIN{exit !(l+0==l && l>=-180 && l<=180)}' \
    || { echo "Invalid longitude (must be -180..180)" >&2; exit 1; }

  if [ -f "$CONFIG_FILE" ] && [ "${FORCE:-0}" != "1" ]; then
    echo "Config already exists at $CONFIG_FILE — re-run with --force to overwrite" >&2
    exit 1
  fi

  mkdir -p "$CONFIG_DIR"
  cat > "$CONFIG_FILE" <<EOF
# Generated by ./install.sh --configure  ($(date -Iseconds))
[weather]
lat = $LAT
lon = $LON
city_name = "$CITY"

[deck]
ssh_host = "$SSH_HOST"
EOF

  echo
  echo " Wrote $CONFIG_FILE"
  echo " Restart the service to apply: systemctl --user restart $UNIT"
}

case "${1:-}" in
  -h|--help) usage 0 ;;
  --configure) do_configure; exit 0 ;;
  --force) FORCE=1 ;;
  "") : ;;  # no args = normal install
  *) echo "Unknown arg: $1" >&2; usage 1 ;;
esac

echo "==> System packages (libhidapi backend, Pillow, fonts; konsole tools optional)"
if command -v apt-get >/dev/null; then
  sudo apt-get update -qq
  # ponytail: `|| true` tolerates unavailable optional packages (qdbus/xdotool
  # names vary by distro) — upgrade: split required vs optional sets and fail
  # loudly on the required ones.
  sudo apt-get install -y libhidapi-libusb0 python3-pil fonts-dejavu-core \
                          tmux qdbus-qt5 xdotool || true
fi

echo "==> Python StreamDeck library"
if ! python3 -c 'import StreamDeck' 2>/dev/null; then
  # PEP 668 systems (Ubuntu 24.04+) need an explicit override or a venv.
  pip install --user streamdeck 2>/dev/null \
    || pip install --user --break-system-packages streamdeck \
    || echo "!! install 'streamdeck' manually (pip/pipx) — import StreamDeck failed"
fi

echo "==> udev rule (uaccess for Stream Deck, vendor 0fd9)"
sudo install -m 0644 "$SRC/udev/70-streamdeck.rules" /etc/udev/rules.d/70-streamdeck.rules
sudo udevadm control --reload-rules
sudo udevadm trigger --action=add --subsystem-match=usb
sudo udevadm trigger --action=add --subsystem-match=hidraw
echo "   (replug the Stream Deck if it was already connected)"

echo "==> deck.py -> $DEST"
mkdir -p "$DEST"
install -m 0755 "$SRC/deck.py" "$DEST/deck.py"

echo "==> systemd --user service"
mkdir -p "$USER_UNIT_DIR"
install -m 0644 "$SRC/systemd/$UNIT" "$USER_UNIT_DIR/$UNIT"
loginctl enable-linger "$USER" 2>/dev/null || true
systemctl --user daemon-reload
systemctl --user enable --now "$UNIT"

echo
echo "Done. Status:"
systemctl --user --no-pager status "$UNIT" | head -5 || true
echo "Logs: journalctl --user -u streamdeck-agentdeck -f"
